version: '2'
services:
    insb:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
        env_file:
            - ./env/insb.env
        network_mode: bridge
        ports:
            - "192.168.128.206:80:80"
            - "192.168.128.206:443:443"
        restart: always
    inshs:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
        env_file:
            - ./env/inshs.env
        network_mode: bridge
        ports:
            - "192.168.128.207:80:80"
            - "192.168.128.207:443:443"
        restart: always
