dnsmasq:
    image: andyshinn/dnsmasq:2.75
    cap_add:
        - NET_ADMIN
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
        - 127.0.0.1:53:53/udp
        - 127.0.0.1:53:53/tcp
    command: -S /.insb.bib.dev.fr/127.0.0.1 -A /.insb.bib.dev.fr/127.0.0.1

insb:
    extends:
        file: ./docker-compose.yml
        service: ezproxy
    volumes:
        - ./config:/usr/local/ezproxy/config
    links:
        - dnsmasq
    environment:
        DNS_ADDR: dnsmasq
        GATE_SUFFIX: bib.dev.fr
    env_file:
        - ./env/insb.env
