version: '3.5'
services:
    verif:
        image: bibcnrs/ezproxy:6.3.5
        ports:
            - 80
            - 443
        environment:
            env: VERIF
            ADMIN_LOGIN: ${ADMIN_LOGIN}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            GATE_SUFFIX: ${GATE_SUFFIX}
            EZ_TICKET_URL: ${EZ_TICKET_URL}
            EZ_TICKET_SECRET: ${EZ_TICKET_SECRET}
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ./logs:/usr/local/ezproxy/logs
        env_file:
            - ./env/verif.env
#        network_mode: bridge
        ports:
            - "192.168.128.212:80:80"
            - "192.168.128.212:443:443"
        restart: always
        networks:
          - bibfrontend
networks:
  bibfrontend:
    external: true
