version: '2'
services:
    in2p3:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/in2p3:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/in2p3.env
        network_mode: bridge
        ports:
            - "192.168.128.201:80:80"
            - "192.168.128.201:443:443"
        restart: always
    inc:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/inc:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/inc.env
        network_mode: bridge
        ports:
            - "192.168.128.202:80:80"
            - "192.168.128.202:443:443"
        restart: always
    inee:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/inee:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/inee.env
        network_mode: bridge
        ports:
            - "192.168.128.203:80:80"
            - "192.168.128.203:443:443"
        restart: always
    inp:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/inp:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/inp.env
        network_mode: bridge
        ports:
            - "192.168.128.204:80:80"
            - "192.168.128.204:443:443"
        restart: always
    ins2i:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/ins2i:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/ins2i.env
        network_mode: bridge
        ports:
            - "192.168.128.205:80:80"
            - "192.168.128.205:443:443"
        restart: always
    insb:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/insb:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/insb.env
        network_mode: bridge
        ports:
            - "192.168.128.206:80:80"
            - "192.168.128.206:443:443"
        restart: always
    inshs:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/inshs:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/inshs.env
        network_mode: bridge
        ports:
            - "192.168.128.207:80:80"
            - "192.168.128.207:443:443"
        restart: always
    insis:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/insis:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/insis.env
        network_mode: bridge
        ports:
            - "192.168.128.208:80:80"
            - "192.168.128.208:443:443"
        restart: always
    insmi:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/insmi:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/insmi.env
        network_mode: bridge
        ports:
            - "192.168.128.209:80:80"
            - "192.168.128.209:443:443"
        restart: always
    insu:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ../ssl/insu:/usr/local/ezproxy/config/ssl
        env_file:
            - ./env/insu.env
        network_mode: bridge
        ports:
            - "192.168.128.210:80:80"
            - "192.168.128.210:443:443"
        restart: always
