version: '2'
services:
    dnsmasq:
        image: andyshinn/dnsmasq:2.75
        cap_add:
            - NET_ADMIN
        volumes:
            - ./dnsmasq.conf:/etc/dnsmasq.conf
        environment:
            http_proxy: ${http_proxy}
            https_proxy: ${https_proxy}
        networks:
            - insb
            - inshs
        ports:
            - 127.0.0.1:53:53/udp
            - 127.0.0.1:53:53/tcp
        command: --no-daemon
    insb:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_dev
        links:
            - dnsmasq
        volumes:
            - ./logs:/usr/local/ezproxy/logs
        env_file:
            - ./env/insb.env
        networks:
            - insb
    inshs:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_dev
        volumes:
            - ./logs:/usr/local/ezproxy/logs
        links:
            - dnsmasq
        env_file:
            - ./env/inshs.env
        networks:
            - inshs
networks:
    insb:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.169.8/29
    inshs:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.169.16/29
