version: '2'
services:
    verif:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_verif
        volumes:
            - ./config:/usr/local/ezproxy/config
            - ./logs:/usr/local/ezproxy/logs
        env_file:
            - ./env/verif.env
        network_mode: bridge
        ports:
            - "192.168.128.212:80:80"
            - "192.168.128.212:443:443"
        restart: always
