version: '2'
services:
    insb:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
        networks:
            - insb
        env_file:
            - ./env/insb.env
    inshs:
        extends:
            file: ./docker-compose.yml
            service: ezproxy_prod
        volumes:
            - ./config:/usr/local/ezproxy/config
        networks:
            - inshs
        env_file:
            - ./env/inshs.env
    # etc...
networks:
    insb:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.169.8/29
    inshs:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.169.16/29
# etc...
